### ISSUE TITLE
Edge case bug?

### ISSUE THREAD

**Issue by lolilolicon** [fogleman/primitive#18]
Looks like `0` is passed to `Intn`?
```
panic: invalid argument to Intn

goroutine 8 [running]:
panic(0x539800, 0xc42000edb0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
math/rand.(*Rand).Intn(0xc4200104a0, 0x0, 0x0)
	/usr/lib/go/src/math/rand/rand.go:116 +0xd0
github.com/fogleman/primitive/primitive.NewRandomEllipse(0x1, 0x1, 0xc4200104a0, 0x0)
	/usr/lib/go/src/github.com/fogleman/primitive/primitive/ellipse.go:22 +0x8d
github.com/fogleman/primitive/primitive.(*Model).RandomState(0xc420072210, 0xc420018600, 0x3, 0x80, 0xc4200104a0, 0x20)
	/usr/lib/go/src/github.com/fogleman/primitive/primitive/model.go:198 +0x3bd
github.com/fogleman/primitive/primitive.(*Model).BestRandomState(0xc420072210, 0xc420018600, 0x3, 0x80, 0x64, 0xc4200104a0, 0x0)
	/usr/lib/go/src/github.com/fogleman/primitive/primitive/model.go:179 +0x7e
github.com/fogleman/primitive/primitive.(*Model).BestHillClimbState(0xc420072210, 0xc420018600, 0x3, 0x80, 0x64, 0x64, 0x2, 0xc4200104a0, 0x0)
	/usr/lib/go/src/github.com/fogleman/primitive/primitive/model.go:162 +0xcf
github.com/fogleman/primitive/primitive.(*Model).runWorker(0xc420072210, 0x3, 0x80, 0x64, 0x64, 0x2, 0xc42005a180)
	/usr/lib/go/src/github.com/fogleman/primitive/primitive/model.go:154 +0x234
created by github.com/fogleman/primitive/primitive.(*Model).runWorkers
	/usr/lib/go/src/github.com/fogleman/primitive/primitive/model.go:136 +0x13b
```

**Comment by fogleman** [comment]
What image and arguments did you run with?

**Comment by lolilolicon** [comment]
I ran this in a batch job; didn't really catch the image being processed that generated this error.
These are small images downloaded then passed to `primitive`. Of the hundreds of images, on which the same arguments are used, this is the one single image that produced this error.
Since randomness is involved, I thought it might just be an edge case of `0`.

**Comment by MelanieCLopez** [comment]
sorry imsont know

**Comment by fogleman** [comment]
I suspected a tiny image. I think some other code changes fixed it anyway.
